[package]
name = "sledgehammer_bindgen"
version = "0.6.0"
authors = ["Evan Almloff <ealmlof1@stumail.jccc.edu>"]
edition = "2021"
description = "Fast batched js bindings"
documentation = "https://docs.rs/sledgehammer_bindgen"
readme = "README.md"
repository = "https://github.com/demonthos/sledgehammer_bindgen/"
license = "MIT"
keywords = ["web", "wasm", "dom"]
categories = ["web-programming", "wasm", "api-bindings"]

[dependencies]
sledgehammer_bindgen_macro = { path = "sledgehammer_bindgen_macro", version = "0.6.0" }
wasm-bindgen = { version = "0.2", optional = true }

[dev-dependencies]
rand = "0.9.0"
getrandom = "0.3"
sledgehammer_utils = "0.3"
wasm-bindgen = "0.2"
wry = { version = "0.51", features = ["devtools"] }
tao = "0.33"

[dev-dependencies.web-sys]
version = "0.3"
features = ["Node", "console"]

[features]
default = []
web = ["wasm-bindgen", "sledgehammer_bindgen_macro/web"]

[workspace]
members = ["sledgehammer_bindgen_macro"]

[[example]]
name = "typed_elements"
required-features = ["web"]

[[example]]
name = "test"
required-features = ["web"]

[[example]]
name = "simple"
required-features = ["web"]

[[example]]
name = "wry"
